added FT2 transfer request flavour(with beneCode and with beneDetail
apibanking/APIBankingASP.NET pull request #2
Opened 2016-11-20 09:15 UTC by Neha1993

2016-11-20 13:05 UTC, akil-rails requested changes

2016-11-20 13:05 UTC, akil-rails commented on APIBankingASP.NET/Models/FundsTransferByCustomerService2.cs
> +            public String beneficiaryAddress1 { get; set; }
why did you have to rename this ? the word 'beneficiary' is redundant/repeating..

2016-11-21 18:56 UTC, Neha1993 commented
fixed review comments and added implemented certificate part

2016-11-22 08:38 UTC, Neha1993 commented on APIBankingASP.NET/Models/FundsTransferByCustomerService2.cs
> +            public String beneficiaryAddress1 { get; set; }
I renamed the variable name to made the clear label Name on UI. Now I have used 'Html.Label' to give the label name instead of using the variable name.

2016-11-22 08:39 UTC, Neha1993 reviewed
Fixed

2016-11-23 04:37 UTC, Neha1993 commented
Removed the code for file transfer from one directory to another, as required was moving from machine to another.

2016-11-23 08:51 UTC, akil-rails approved these changes

2016-11-23 08:51 UTC, akil-rails commented on APIBankingASP.NET/Controllers/FundsTransferByCustomerService2Controller.cs
> +                string targetPath = @"\Users\Public\Certificate\";
Where is it documented that a file that is uploaded will be stored in this location?
This is the path for that was used in the Console application, it will not be the same for the web application.

2016-11-23 08:52 UTC, merged